/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\@vuepress\\plugin-medium-zoom\\clientRootMixin.js"
import m3 from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m4 from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4
]