/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "H:\\个人\\OneDrive\\文档\\个人\\mtblot\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3486bb7c",
    path: "/CitiesLine/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3486bb7c").then(next)
    },
  },
  {
    path: "/CitiesLine/index.html",
    redirect: "/CitiesLine/"
  },
  {
    name: "v-dc263a18",
    path: "/CocoCss/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc263a18").then(next)
    },
  },
  {
    path: "/CocoCss/index.html",
    redirect: "/CocoCss/"
  },
  {
    name: "v-16fa6fe2",
    path: "/CocoCss/VariableBorder/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16fa6fe2").then(next)
    },
  },
  {
    path: "/CocoCss/VariableBorder/index.html",
    redirect: "/CocoCss/VariableBorder/"
  },
  {
    name: "v-7d67ac2a",
    path: "/Demos/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d67ac2a").then(next)
    },
  },
  {
    path: "/Demos/index.html",
    redirect: "/Demos/"
  },
  {
    name: "v-6133c2bc",
    path: "/NetEasyMusic/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6133c2bc").then(next)
    },
  },
  {
    path: "/NetEasyMusic/index.html",
    redirect: "/NetEasyMusic/"
  },
  {
    name: "v-5a26ec82",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a26ec82").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c3bb4a80",
    path: "/Potion-Making/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c3bb4a80").then(next)
    },
  },
  {
    path: "/Potion-Making/index.html",
    redirect: "/Potion-Making/"
  },
  {
    name: "v-9f6b9dd6",
    path: "/ReadingNotes/ClearCode/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f6b9dd6").then(next)
    },
  },
  {
    path: "/ReadingNotes/ClearCode/index.html",
    redirect: "/ReadingNotes/ClearCode/"
  },
  {
    name: "v-4b2f3839",
    path: "/ReadingNotes/ProfessionalJavaScriptForWebDevelopers/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b2f3839").then(next)
    },
  },
  {
    path: "/ReadingNotes/ProfessionalJavaScriptForWebDevelopers/index.html",
    redirect: "/ReadingNotes/ProfessionalJavaScriptForWebDevelopers/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-323b9794",
    path: "/tag/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-323b9794").then(next)
    },
    meta: {"pid":"tags","id":"css"}
  },
  {
    path: "/tag/css/index.html",
    redirect: "/tag/css/"
  },
  {
    name: "v-1528037c",
    path: "/tag/demo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1528037c").then(next)
    },
    meta: {"pid":"tags","id":"demo"}
  },
  {
    path: "/tag/demo/index.html",
    redirect: "/tag/demo/"
  },
  {
    name: "v-14055bfa",
    path: "/tag/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-14055bfa").then(next)
    },
    meta: {"pid":"tags","id":"node"}
  },
  {
    path: "/tag/node/index.html",
    redirect: "/tag/node/"
  },
  {
    name: "v-7418fe36",
    path: "/tag/linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7418fe36").then(next)
    },
    meta: {"pid":"tags","id":"linux"}
  },
  {
    path: "/tag/linux/index.html",
    redirect: "/tag/linux/"
  },
  {
    name: "v-5ab47251",
    path: "/tag/服务器/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5ab47251").then(next)
    },
    meta: {"pid":"tags","id":"服务器"}
  },
  {
    path: "/tag/服务器/index.html",
    redirect: "/tag/服务器/"
  },
  {
    name: "v-0cd5191c",
    path: "/tag/魔药学/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0cd5191c").then(next)
    },
    meta: {"pid":"tags","id":"魔药学"}
  },
  {
    path: "/tag/魔药学/index.html",
    redirect: "/tag/魔药学/"
  },
  {
    name: "v-71f849b4",
    path: "/tag/读书笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-71f849b4").then(next)
    },
    meta: {"pid":"tags","id":"读书笔记"}
  },
  {
    path: "/tag/读书笔记/index.html",
    redirect: "/tag/读书笔记/"
  },
  {
    name: "v-07cbb473",
    path: "/tag/笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-07cbb473").then(next)
    },
    meta: {"pid":"tags","id":"笔记"}
  },
  {
    path: "/tag/笔记/index.html",
    redirect: "/tag/笔记/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    name: "v-7f0d6caa",
    path: "/categories/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0d6caa").then(next)
    },
    meta: {"pid":"categories","id":"css"}
  },
  {
    path: "/categories/css/index.html",
    redirect: "/categories/css/"
  },
  {
    name: "v-62a7d44e",
    path: "/categories/demo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-62a7d44e").then(next)
    },
    meta: {"pid":"categories","id":"demo"}
  },
  {
    path: "/categories/demo/index.html",
    redirect: "/categories/demo/"
  },
  {
    name: "v-7efd6f93",
    path: "/categories/API/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efd6f93").then(next)
    },
    meta: {"pid":"categories","id":"API"}
  },
  {
    path: "/categories/API/index.html",
    redirect: "/categories/API/"
  },
  {
    name: "v-6339280f",
    path: "/categories/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6339280f").then(next)
    },
    meta: {"pid":"categories","id":"node"}
  },
  {
    path: "/categories/node/index.html",
    redirect: "/categories/node/"
  },
  {
    name: "v-00326c59",
    path: "/categories/linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-00326c59").then(next)
    },
    meta: {"pid":"categories","id":"linux"}
  },
  {
    path: "/categories/linux/index.html",
    redirect: "/categories/linux/"
  },
  {
    name: "v-41e61d1f",
    path: "/categories/frontEnd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-41e61d1f").then(next)
    },
    meta: {"pid":"categories","id":"frontEnd"}
  },
  {
    path: "/categories/frontEnd/index.html",
    redirect: "/categories/frontEnd/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]