/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rrafa",
  "description": "霍格沃兹，qq：1162965298",
  "base": "/mt-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/mt-blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "场景化造景记录",
      "frontmatter": {},
      "regularPath": "/CitiesLine/",
      "relativePath": "CitiesLine/README.md",
      "key": "v-3486bb7c",
      "path": "/CitiesLine/",
      "headers": [
        {
          "level": 2,
          "title": "场景化造景记录",
          "slug": "场景化造景记录"
        }
      ]
    },
    {
      "title": "Coco的Css文章练习",
      "frontmatter": {
        "title": "Coco的Css文章练习",
        "date": "2021-1-20",
        "categories": [
          "前端",
          "css"
        ],
        "tags": [
          "css",
          "demo"
        ]
      },
      "regularPath": "/CocoCss/",
      "relativePath": "CocoCss/README.md",
      "key": "v-dc263a18",
      "path": "/CocoCss/",
      "headers": [
        {
          "level": 2,
          "title": "第一个是一个心形",
          "slug": "第一个是一个心形"
        }
      ]
    },
    {
      "title": "CSS可变的边框图",
      "frontmatter": {
        "title": "CSS可变的边框图",
        "date": "2021/1/22",
        "categories": [
          "前端",
          "css"
        ],
        "tags": [
          "css",
          "demo"
        ]
      },
      "regularPath": "/CocoCss/VariableBorder/",
      "relativePath": "CocoCss/VariableBorder/README.md",
      "key": "v-16fa6fe2",
      "path": "/CocoCss/VariableBorder/",
      "headers": [
        {
          "level": 2,
          "title": "复习border",
          "slug": "复习border"
        },
        {
          "level": 2,
          "title": "先实现一个简单的demo",
          "slug": "先实现一个简单的demo"
        },
        {
          "level": 2,
          "title": "虚线边框动画",
          "slug": "虚线边框动画"
        }
      ]
    },
    {
      "title": "Demo小集合，从最开始到现在的种种demo练习",
      "frontmatter": {
        "title": "Demo小集合，从最开始到现在的种种demo练习",
        "date": "2019-8-2",
        "categories": [
          "前端",
          "demo"
        ],
        "tags": [
          "demo"
        ]
      },
      "regularPath": "/Demos/",
      "relativePath": "Demos/README.md",
      "key": "v-7d67ac2a",
      "path": "/Demos/"
    },
    {
      "title": "网易云音乐API——线上服务器demo记录",
      "frontmatter": {
        "title": "网易云音乐API——线上服务器demo记录",
        "date": "2021-4-23",
        "categories": [
          "API",
          "node",
          "linux"
        ],
        "tags": [
          "node",
          "linux",
          "服务器"
        ]
      },
      "regularPath": "/NetEasyMusic/",
      "relativePath": "NetEasyMusic/README.md",
      "key": "v-6133c2bc",
      "path": "/NetEasyMusic/",
      "headers": [
        {
          "level": 2,
          "title": "需要说明",
          "slug": "需要说明"
        },
        {
          "level": 2,
          "title": "需要的内容",
          "slug": "需要的内容"
        },
        {
          "level": 2,
          "title": "获取管理员权限",
          "slug": "获取管理员权限"
        },
        {
          "level": 2,
          "title": "安装node",
          "slug": "安装node"
        },
        {
          "level": 2,
          "title": "安装git",
          "slug": "安装git"
        },
        {
          "level": 2,
          "title": "配置git",
          "slug": "配置git"
        },
        {
          "level": 2,
          "title": "配置ssh",
          "slug": "配置ssh"
        },
        {
          "level": 2,
          "title": "clone网易云的代码",
          "slug": "clone网易云的代码"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": "ture",
        "heroImage": "/sin.png",
        "heroImageStyle": {
          "maxHeight": "200px",
          "display": "block",
          "margin": "6rem auto 1.5rem",
          "borderRadius": "50%",
          "boxShadow": "0 5px 18px rgba(0,0,0,0.2)"
        },
        "heroText": "斯内普"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5a26ec82",
      "path": "/"
    },
    {
      "title": "《高级魔药制作-Advanced Potion-Making》",
      "frontmatter": {
        "title": "《高级魔药制作-Advanced Potion-Making》",
        "date": "2019-3-23",
        "categories": [
          "demo"
        ],
        "tags": [
          "魔药学"
        ]
      },
      "regularPath": "/Potion-Making/",
      "relativePath": "Potion-Making/README.md",
      "key": "v-c3bb4a80",
      "path": "/Potion-Making/",
      "headers": [
        {
          "level": 2,
          "title": "序言",
          "slug": "序言"
        },
        {
          "level": 2,
          "title": "制作魔药的器材",
          "slug": "制作魔药的器材"
        },
        {
          "level": 2,
          "title": "魔药熬制七种方法",
          "slug": "魔药熬制七种方法"
        },
        {
          "level": 3,
          "title": "煎煮（decoction)",
          "slug": "煎煮-decoction"
        },
        {
          "level": 3,
          "title": "冲泡（infusion）",
          "slug": "冲泡-infusion"
        },
        {
          "level": 3,
          "title": "浸渍（macerate)",
          "slug": "浸渍-macerate"
        },
        {
          "level": 3,
          "title": "油膏（ointment）：",
          "slug": "油膏-ointment"
        },
        {
          "level": 3,
          "title": "敷剂（poultice）",
          "slug": "敷剂-poultice"
        },
        {
          "level": 3,
          "title": "酊剂（tincture）",
          "slug": "酊剂-tincture"
        },
        {
          "level": 3,
          "title": "洗剂（wash）",
          "slug": "洗剂-wash"
        },
        {
          "level": 2,
          "title": "活地狱汤剂",
          "slug": "活地狱汤剂"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料"
        },
        {
          "level": 3,
          "title": "制作方法",
          "slug": "制作方法"
        },
        {
          "level": 3,
          "title": "解药",
          "slug": "解药"
        },
        {
          "level": 2,
          "title": "欢欣剂 Elixir to Induce Euphoria",
          "slug": "欢欣剂-elixir-to-induce-euphoria"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-2"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-2"
        },
        {
          "level": 3,
          "title": "制作方法",
          "slug": "制作方法-2"
        },
        {
          "level": 3,
          "title": "注意：",
          "slug": "注意"
        },
        {
          "level": 2,
          "title": "打嗝药水（Hiccuping Solution）",
          "slug": "打嗝药水-hiccuping-solution"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-3"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-3"
        },
        {
          "level": 3,
          "title": "制作方法：",
          "slug": "制作方法-3"
        },
        {
          "level": 2,
          "title": "美丽药剂Beautification Potion",
          "slug": "美丽药剂beautification-potion"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-4"
        },
        {
          "level": 3,
          "title": "第一阶段",
          "slug": "第一阶段"
        },
        {
          "level": 3,
          "title": "第二阶段",
          "slug": "第二阶段"
        },
        {
          "level": 2,
          "title": "★狐媚子灭剂Doxycide（第十八页）",
          "slug": "★狐媚子灭剂doxycide-第十八页"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-5"
        },
        {
          "level": 3,
          "title": "第一阶段",
          "slug": "第一阶段-2"
        },
        {
          "level": 3,
          "title": "第二阶段",
          "slug": "第二阶段-2"
        },
        {
          "level": 2,
          "title": "永恒药剂（Everlasting Elixirs）",
          "slug": "永恒药剂-everlasting-elixirs"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-6"
        },
        {
          "level": 3,
          "title": "制作方法",
          "slug": "制作方法-4"
        },
        {
          "level": 2,
          "title": "复方汤剂 (Polyjuice Potion)",
          "slug": "复方汤剂-polyjuice-potion"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-7"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-4"
        },
        {
          "level": 3,
          "title": "制作过程：第一阶段",
          "slug": "制作过程-第一阶段"
        },
        {
          "level": 3,
          "title": "第二阶段",
          "slug": "第二阶段-3"
        },
        {
          "level": 2,
          "title": "迷情剂Amortentia",
          "slug": "迷情剂amortentia"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-8"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-5"
        },
        {
          "level": 3,
          "title": "制作方法：第一阶段",
          "slug": "制作方法-第一阶段"
        },
        {
          "level": 3,
          "title": "第二阶段",
          "slug": "第二阶段-4"
        },
        {
          "level": 2,
          "title": "福灵剂Felix Felicis",
          "slug": "福灵剂felix-felicis"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果-9"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-6"
        },
        {
          "level": 3,
          "title": "制作方法：",
          "slug": "制作方法-5"
        },
        {
          "level": 2,
          "title": "解药和戈巴洛特第三定律",
          "slug": "解药和戈巴洛特第三定律"
        },
        {
          "level": 2,
          "title": "广谱解药Antidote to Common Poisons",
          "slug": "广谱解药antidote-to-common-poisons"
        },
        {
          "level": 3,
          "title": "材料",
          "slug": "材料-7"
        },
        {
          "level": 3,
          "title": "步骤：",
          "slug": "步骤"
        }
      ]
    },
    {
      "title": "《CleanCode》-笔记",
      "frontmatter": {
        "title": "《CleanCode》-笔记",
        "date": "2021-1-27",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "读书笔记"
        ]
      },
      "regularPath": "/ReadingNotes/ClearCode/",
      "relativePath": "ReadingNotes/ClearCode/README.md",
      "key": "v-9f6b9dd6",
      "path": "/ReadingNotes/ClearCode/",
      "headers": [
        {
          "level": 2,
          "title": "最重要的！命名技巧",
          "slug": "最重要的-命名技巧"
        },
        {
          "level": 3,
          "title": "1.1 名副其实的命名",
          "slug": "_1-1-名副其实的命名"
        },
        {
          "level": 3,
          "title": "1.2 避免误导",
          "slug": "_1-2-避免误导"
        },
        {
          "level": 3,
          "title": "1.3 区分的意义",
          "slug": "_1-3-区分的意义"
        },
        {
          "level": 3,
          "title": "1.4 名称可读",
          "slug": "_1-4-名称可读"
        },
        {
          "level": 3,
          "title": "1.5 名称可搜索",
          "slug": "_1-5-名称可搜索"
        },
        {
          "level": 3,
          "title": "1.6 成员前缀",
          "slug": "_1-6-成员前缀"
        },
        {
          "level": 3,
          "title": "1.7 避免思维映射",
          "slug": "_1-7-避免思维映射"
        },
        {
          "level": 3,
          "title": "1.8 类名",
          "slug": "_1-8-类名"
        },
        {
          "level": 3,
          "title": "1.9 方法名",
          "slug": "_1-9-方法名"
        },
        {
          "level": 3,
          "title": "1.10 每一个概念对应一个词",
          "slug": "_1-10-每一个概念对应一个词"
        },
        {
          "level": 3,
          "title": "1.11 别用双关语",
          "slug": "_1-11-别用双关语"
        },
        {
          "level": 3,
          "title": "1.12 使用解决方案领域的名称",
          "slug": "_1-12-使用解决方案领域的名称"
        },
        {
          "level": 3,
          "title": "1.13 添加有意义的语境",
          "slug": "_1-13-添加有意义的语境"
        },
        {
          "level": 2,
          "title": "函数的优化",
          "slug": "函数的优化"
        },
        {
          "level": 3,
          "title": "2.1 短小",
          "slug": "_2-1-短小"
        },
        {
          "level": 3,
          "title": "2.2 只做一件事",
          "slug": "_2-2-只做一件事"
        },
        {
          "level": 3,
          "title": "2.3 每一个函数一个抽象层级",
          "slug": "_2-3-每一个函数一个抽象层级"
        },
        {
          "level": 3,
          "title": "2.4 switch语句",
          "slug": "_2-4-switch语句"
        },
        {
          "level": 3,
          "title": "2.5 使用描述性的名称",
          "slug": "_2-5-使用描述性的名称"
        },
        {
          "level": 3,
          "title": "2.6 函数参数",
          "slug": "_2-6-函数参数"
        },
        {
          "level": 3,
          "title": "2.7 无副作用",
          "slug": "_2-7-无副作用"
        },
        {
          "level": 3,
          "title": "2.8 分隔指令与询问",
          "slug": "_2-8-分隔指令与询问"
        },
        {
          "level": 3,
          "title": "2.9 使用异常替代返回错误码",
          "slug": "_2-9-使用异常替代返回错误码"
        },
        {
          "level": 3,
          "title": "2.10 不要重复",
          "slug": "_2-10-不要重复"
        },
        {
          "level": 3,
          "title": "2.11 结构化编程",
          "slug": "_2-11-结构化编程"
        }
      ]
    },
    {
      "title": "JavaScript高级程序编程笔记",
      "frontmatter": {
        "title": "JavaScript高级程序编程笔记",
        "date": "2019-11-3",
        "categories": [
          "前端"
        ],
        "tags": [
          "笔记"
        ]
      },
      "regularPath": "/ReadingNotes/ProfessionalJavaScriptForWebDevelopers/",
      "relativePath": "ReadingNotes/ProfessionalJavaScriptForWebDevelopers/README.md",
      "key": "v-4b2f3839",
      "path": "/ReadingNotes/ProfessionalJavaScriptForWebDevelopers/"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "demo Tags"
      },
      "regularPath": "/tag/demo/",
      "key": "v-1528037c",
      "path": "/tag/demo/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "node Tags"
      },
      "regularPath": "/tag/node/",
      "key": "v-14055bfa",
      "path": "/tag/node/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "linux Tags"
      },
      "regularPath": "/tag/linux/",
      "key": "v-7418fe36",
      "path": "/tag/linux/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "服务器 Tags"
      },
      "regularPath": "/tag/%E6%9C%8D%E5%8A%A1%E5%99%A8/",
      "key": "v-5ab47251",
      "path": "/tag/服务器/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "魔药学 Tags"
      },
      "regularPath": "/tag/%E9%AD%94%E8%8D%AF%E5%AD%A6/",
      "key": "v-0cd5191c",
      "path": "/tag/魔药学/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "读书笔记 Tags"
      },
      "regularPath": "/tag/%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0/",
      "key": "v-71f849b4",
      "path": "/tag/读书笔记/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "笔记 Tags"
      },
      "regularPath": "/tag/%E7%AC%94%E8%AE%B0/",
      "key": "v-07cbb473",
      "path": "/tag/笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "css Categories"
      },
      "regularPath": "/categories/css/",
      "key": "v-7f0d6caa",
      "path": "/categories/css/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "demo Categories"
      },
      "regularPath": "/categories/demo/",
      "key": "v-62a7d44e",
      "path": "/categories/demo/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "API Categories"
      },
      "regularPath": "/categories/API/",
      "key": "v-7efd6f93",
      "path": "/categories/API/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "node Categories"
      },
      "regularPath": "/categories/node/",
      "key": "v-6339280f",
      "path": "/categories/node/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "linux Categories"
      },
      "regularPath": "/categories/linux/",
      "key": "v-00326c59",
      "path": "/categories/linux/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "frontEnd Categories"
      },
      "regularPath": "/categories/frontEnd/",
      "key": "v-41e61d1f",
      "path": "/categories/frontEnd/"
    }
  ],
  "themeConfig": {
    "logo": "/favicon.ico",
    "type": "blog",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "一个颜色选取工具",
        "link": "http://rrafa.icu/",
        "icon": "reco-color"
      },
      {
        "text": "读书笔记(Clean Code)",
        "link": "./ReadingNotes/ClearCode/"
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "sidebar": "auto",
    "sidebarDepth": 3,
    "friendLink": [
      {
        "title": "一个国风色彩网站",
        "desc": "一个简单的色彩选择网站",
        "logo": "/favicon.ico",
        "link": "http://rrafa.icu/"
      },
      {
        "title": "https://bladexue.github.io/",
        "desc": "react",
        "link": "http://rrafa.icu/"
      }
    ]
  }
}