/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-dc263a18",
        "v-16fa6fe2"
      ]
    },
    "demo": {
      "key": "demo",
      "scope": "tags",
      "path": "/tag/demo/",
      "pageKeys": [
        "v-dc263a18",
        "v-16fa6fe2",
        "v-7d67ac2a"
      ]
    },
    "node": {
      "key": "node",
      "scope": "tags",
      "path": "/tag/node/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "linux": {
      "key": "linux",
      "scope": "tags",
      "path": "/tag/linux/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "服务器": {
      "key": "服务器",
      "scope": "tags",
      "path": "/tag/服务器/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "魔药学": {
      "key": "魔药学",
      "scope": "tags",
      "path": "/tag/魔药学/",
      "pageKeys": [
        "v-c3bb4a80"
      ]
    },
    "读书笔记": {
      "key": "读书笔记",
      "scope": "tags",
      "path": "/tag/读书笔记/",
      "pageKeys": [
        "v-9f6b9dd6"
      ]
    },
    "笔记": {
      "key": "笔记",
      "scope": "tags",
      "path": "/tag/笔记/",
      "pageKeys": [
        "v-4b2f3839"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-dc263a18",
        "v-16fa6fe2",
        "v-7d67ac2a",
        "v-4b2f3839"
      ]
    },
    "css": {
      "key": "css",
      "scope": "categories",
      "path": "/categories/css/",
      "pageKeys": [
        "v-dc263a18",
        "v-16fa6fe2"
      ]
    },
    "demo": {
      "key": "demo",
      "scope": "categories",
      "path": "/categories/demo/",
      "pageKeys": [
        "v-7d67ac2a",
        "v-c3bb4a80"
      ]
    },
    "API": {
      "key": "API",
      "scope": "categories",
      "path": "/categories/API/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "node": {
      "key": "node",
      "scope": "categories",
      "path": "/categories/node/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "linux": {
      "key": "linux",
      "scope": "categories",
      "path": "/categories/linux/",
      "pageKeys": [
        "v-6133c2bc"
      ]
    },
    "frontEnd": {
      "key": "frontEnd",
      "scope": "categories",
      "path": "/categories/frontEnd/",
      "pageKeys": [
        "v-9f6b9dd6"
      ]
    }
  },
  "timeline": {}
}